FROM gentoo/portage:20201121 as portage

# image is based on stage3-amd64
FROM gentoo/stage3-amd64:20200904

# copy the entire portage volume in
COPY --from=portage /var/db/repos/gentoo /var/db/repos/gentoo

RUN emerge -qv \
    dev-util/catalyst \
    net-misc/curl